# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [29]:
import pandas as pd
ins_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
ins_df

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
ins_df.columns = ins_df.columns.str.lower().str.strip().str.replace(" ", "_")
ins_df

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [31]:
ins_df["gender"].value_counts()

gender
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

In [32]:
ins_df["gender"] = ins_df["gender"].replace({
    "Male" : "M",
    "female" : "F",
    "Femal" : "F"
})

In [33]:
ins_df["st"].value_counts()

st
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [34]:
ins_df["st"] = ins_df["st"].replace({
    "Cali" : "California",
    "WA" : "Washington",
    "AZ" : "Arizona"
})

In [35]:
ins_df["education"].value_counts()

education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

In [36]:
ins_df["education"] = ins_df["education"].replace({
    "Bachelors" : "Bachelor"
})

In [37]:
ins_df["customer_lifetime_value"] = ins_df["customer_lifetime_value"].str.replace("%", "", regex=False)

In [38]:
ins_df["vehicle_class"].value_counts()
ins_df["vehicle_class"] = ins_df["vehicle_class"].replace({
    "Sports Car" : "Luxury",
    "Luxury SUV" : "Luxury",
    "Luxury Car" : "Luxury"
})

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [39]:
ins_df.dtypes
ins_df["customer_lifetime_value"] = ins_df["customer_lifetime_value"].astype(float)

In [40]:
ins_df["number_of_open_complaints"].unique()

<ArrowStringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

In [41]:
ins_df["number_of_open_complaints"] = ins_df["number_of_open_complaints"].str.split("/").str[1]

In [43]:
ins_df["number_of_open_complaints"].value_counts()

number_of_open_complaints
0    830
1    138
2     50
3     34
4     13
5      6
Name: count, dtype: int64

In [45]:
ins_df["number_of_open_complaints"] = ins_df["number_of_open_complaints"].astype("Int64")

In [46]:
ins_df["number_of_open_complaints"]

0          0
1          0
2          0
3          0
4          0
        ...
4003    <NA>
4004    <NA>
4005    <NA>
4006    <NA>
4007    <NA>
Name: number_of_open_complaints, Length: 4008, dtype: Int64

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [48]:
ins_df.isnull().sum()

customer                     2937
st                           2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [49]:
ins_df.isnull().all(axis=1).sum()

np.int64(2937)

In [51]:
ins_df = ins_df.dropna(how = "all")

In [52]:
ins_df.isnull().sum()

customer                       0
st                             0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [54]:
ins_df["gender"].value_counts()

gender
F    502
M    452
Name: count, dtype: int64

In [56]:
ins_df["gender"] = ins_df["gender"].fillna("Unknown")

In [57]:
ins_df["gender"].value_counts()

gender
F          502
M          452
Unknown    117
Name: count, dtype: int64

In [60]:
ins_df[ins_df["customer_lifetime_value"].isnull()]

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Unknown,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
78,SP81997,Washington,F,Master,NaN,41275.0,96.0,0,Personal Auto,Four-Door Car,41.122303
988,GT62080,Washington,M,High School or Below,NaN,55561.0,63.0,0,Personal Auto,Four-Door Car,227.872071

In [61]:
ins_df["customer_lifetime_value"].median()

np.float64(588174.235)

In [63]:
ins_df["customer_lifetime_value"] = ins_df["customer_lifetime_value"].fillna(ins_df["customer_lifetime_value"].median())

In [67]:
ins_df["customer_lifetime_value"].isnull().sum()

np.int64(0)

In [68]:
ins_df.isnull().sum()

customer                     0
st                           0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [69]:
ins_df.dtypes

customer                         str
st                               str
gender                           str
education                        str
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints      Int64
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

In [70]:
ins_df["customer_lifetime_value"] = ins_df["customer_lifetime_value"].astype(int)
ins_df["income"] = ins_df["income"].astype(int)
ins_df["monthly_premium_auto"] = ins_df["monthly_premium_auto"].astype(int)
ins_df["total_claim_amount"] = ins_df["total_claim_amount"].astype(int)

In [71]:
ins_df.dtypes

customer                       str
st                             str
gender                         str
education                      str
customer_lifetime_value      int64
income                       int64
monthly_premium_auto         int64
number_of_open_complaints    Int64
policy_type                    str
vehicle_class                  str
total_claim_amount           int64
dtype: object

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [73]:
ins_df.duplicated().sum()

np.int64(0)

In [76]:
ins_df = ins_df.reset_index(drop=True)

In [77]:
ins_df.to_csv("cleaned_insurance.csv", index=False)

In [78]:
pd.read_csv("cleaned_insurance.csv").head(10)

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Unknown,Master,588174,0,1000,0,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,F,Bachelor,697953,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,F,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,M,Bachelor,764586,0,106,0,Corporate Auto,SUV,529
4,GA49547,Washington,M,High School or Below,536307,36357,68,0,Personal Auto,Four-Door Car,17
5,OC83172,Oregon,F,Bachelor,825629,62902,69,0,Personal Auto,Two-Door Car,159
6,XZ87318,Oregon,F,College,538089,55350,67,0,Corporate Auto,Four-Door Car,321
7,CF85061,Arizona,M,Master,721610,0,101,0,Corporate Auto,Four-Door Car,363
8,DY87989,Oregon,M,Bachelor,2412750,14072,71,0,Corporate Auto,Four-Door Car,511
9,BQ94931,Oregon,F,College,738817,28812,93,0,Special Auto,Four-Door Car,425

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [ ]:
# Your code here